config/routes.rb
Depot::Application.routes.draw do
  get "store/index"

  resources :things

  resources :products

  root :to => 'store#index', :as => 'store'

end

app/models/product.rb
class Product < ActiveRecord::Base
	default_scope :order => 'title'

	validates(:title, :description, :image_url, :presence => true)
  	validates(:price, :numericality => {:greater_than_or_equal_to => 0.01})
  	validates(:title, :uniqueness =>true)
  	validates(:image_url, :format => { 
  		:with => %r{\.(gif|jpg|png)$}i, 
  		:message => 'must be  a URL for GIF, jpg, or png image.'
  		})
  attr_accessible :description, :image_url, :price, :title
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  attr_accessible :description, :image_url, :price, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  	@products = Product.all
  end
  
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  # GET /things
  # GET /things.json
  def index
    @things = Thing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @things }
    end
  end

  # GET /things/1
  # GET /things/1.json
  def show
    @thing = Thing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /things/new
  # GET /things/new.json
  def new
    @thing = Thing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /things/1/edit
  def edit
    @thing = Thing.find(params[:id])
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(params[:thing])

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render json: @thing, status: :created, location: @thing }
      else
        format.html { render action: "new" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /things/1
  # PUT /things/1.json
  def update
    @thing = Thing.find(params[:id])

    respond_to do |format|
      if @thing.update_attributes(params[:thing])
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing = Thing.find(params[:id])
    @thing.destroy

    respond_to do |format|
      format.html { redirect_to things_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
	@page_title || "Pragmatic Bookshelf"
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="store">
	<div id="banner">
		<%= image_tag("logo.png") %>
		<%= @page_title || "Pragmatic Bookshelf" %>
	</div>
	<div id="columns">
		<div id="side">
			<a href="http://www....">Home</a><br>
			<a href="http://www..../faq">Questions</a><br>
			<a href="http://www..../news">News</a><br>
			<a href="http://www..../contact">Contact</a><br>
		</div>
		<div id="main">
			<%= yield %>
		</div>
	</div>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows =>6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div id="product_list">
<h1>Listing products</h1>

  <table>
  <% @products.each do |product| %>
    <tr class ="<%=cycle('list_line_odd', 'list_line_even') %>">
      <td>
          <%= image_tag(product.image_url, :class => 'list_image') %>
      </td>

      <td class="list_description">
        <dl>
          <dt><%= product.title %></dt>
          <dd><%= truncate(strip_tags(product.description), :length =>80) %></dd>
        </dl>
      </td>

      <td class="list_actions">
        <%= link_to 'Show', product %><br>
        <%= link_to 'Edit', edit_product_path(product) %><br>
        <%= button_to 'Destroy', product, 
        :data =>{:confirm=>'text'},
        :method=>:delete  %>
      </td>
    </tr>
  <% end %>
</table>
</div>


<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @product.image_url %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/store/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1> Your Pragmatic Catalog</h1>

<% @products.each do |product| %>
	<div class="entry">
		<%= image_tag(product.image_url) %>
		<h3><%= product.title %></h3>
		<%= sanitize(product.description) %>
		<div class = "price_line">
			<span class="price"><%= number_to_currency(product.price) %></span>
		</div>
	</div>
<% end %>

app/views/things/_form.html.erb
<%= form_for(@thing) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/things/edit.html.erb
<h1>Editing thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/index.html.erb
<h1>Listing things</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Image url</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @things.each do |thing| %>
  <tr>
    <td><%= thing.title %></td>
    <td><%= thing.description %></td>
    <td><%= thing.image_url %></td>
    <td><%= thing.price %></td>
    <td><%= link_to 'Show', thing %></td>
    <td><%= link_to 'Edit', edit_thing_path(thing) %></td>
    <td><%= link_to 'Destroy', thing, method: :delete, :confirm: 'Are you sure?'  %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Thing', new_thing_path %>

app/views/things/new.html.erb
<h1>New thing</h1>

<%= render 'form' %>

<%= link_to 'Back', things_path %>

app/views/things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @thing.title %>
</p>

<p>
  <b>Description:</b>
  <%= @thing.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @thing.image_url %>
</p>

<p>
  <b>Price:</b>
  <%= @thing.price %>
</p>


<%= link_to 'Edit', edit_thing_path(@thing) %> |
<%= link_to 'Back', things_path %>